# Generated by Django 4.0.5 on 2023-04-05 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsdeviceprocessors',
            name='items',
        ),
        migrations.AddField(
            model_name='itemsdeviceprocessors',
            name='items_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
