# Generated by Django 4.1 on 2022-08-31 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computers',
            options={},
        ),
    ]
