# Generated by Django 4.0.5 on 2023-04-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_remove_itemsdeviceprocessors_items_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsSoftwarelicenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_id', models.PositiveIntegerField()),
                ('itemtype', models.CharField(max_length=100)),
                ('softwarelicenses_id', models.PositiveIntegerField()),
                ('is_deleted', models.IntegerField()),
                ('is_dynamic', models.IntegerField()),
            ],
            options={
                'db_table': 'items_softwarelicenses',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ItemsSoftwareversions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_id', models.PositiveIntegerField()),
                ('itemtype', models.CharField(max_length=100)),
                ('softwareversions_id', models.PositiveIntegerField()),
                ('is_deleted_item', models.IntegerField()),
                ('is_template_item', models.IntegerField()),
                ('entities_id', models.PositiveIntegerField()),
                ('is_deleted', models.IntegerField()),
                ('is_dynamic', models.IntegerField()),
                ('date_install', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'items_softwareversions',
                'managed': True,
                'unique_together': {('itemtype', 'items_id', 'softwareversions_id')},
            },
        ),
    ]
