# Generated by Django 4.1 on 2022-08-31 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_computers_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computers',
            options={'managed': False},
        ),
    ]
