# Generated by Django 4.0.5 on 2023-04-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_itemssoftwarelicenses_itemssoftwareversions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemssoftwareversions',
            name='date_install',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
