# Generated by Django 4.0.5 on 2023-07-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_alter_itemssoftwareversions_date_install'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsdevicesimcards',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
