# Generated by Django 4.0.5 on 2022-11-08 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_autoupdatesystems_entitiesknowbaseitems_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snmpcredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('snmpversion', models.CharField(max_length=8)),
                ('community', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('authentication', models.CharField(blank=True, max_length=255, null=True)),
                ('auth_passphrase', models.CharField(blank=True, max_length=255, null=True)),
                ('encryption', models.CharField(blank=True, max_length=255, null=True)),
                ('priv_passphrase', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.IntegerField()),
            ],
            options={
                'db_table': 'snmpcredentials',
                'managed': True,
            },
        ),
    ]
