# Generated by Django 4.0.5 on 2022-12-11 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_alter_cables_cablestrands_alter_cables_cabletypes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computersitems',
            name='itemtype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='monitors',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='snmpcredentials',
            name='snmpversion',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
