# Generated by Django 4.0.5 on 2022-11-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_snmpcredentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rackmodels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('product_number', models.CharField(blank=True, max_length=255, null=True)),
                ('date_mod', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(blank=True, null=True)),
                ('pictures', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rackmodels',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Racktypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entities_id', models.PositiveIntegerField()),
                ('is_recursive', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(blank=True, null=True)),
                ('date_mod', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'racktypes',
                'managed': True,
            },
        ),
    ]
