# Generated by Django 4.0.5 on 2022-11-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_rackmodels_racktypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dcrooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('entities_id', models.PositiveIntegerField()),
                ('is_recursive', models.IntegerField()),
                ('locations_id', models.PositiveIntegerField()),
                ('vis_cols', models.IntegerField(blank=True, null=True)),
                ('vis_rows', models.IntegerField(blank=True, null=True)),
                ('blueprint', models.TextField(blank=True, null=True)),
                ('datacenters_id', models.PositiveIntegerField()),
                ('is_deleted', models.IntegerField()),
                ('date_mod', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dcrooms',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Enclosuremodels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('product_number', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.IntegerField()),
                ('required_units', models.IntegerField()),
                ('depth', models.FloatField()),
                ('power_connections', models.IntegerField()),
                ('power_consumption', models.IntegerField()),
                ('is_half_rack', models.IntegerField()),
                ('picture_front', models.TextField(blank=True, null=True)),
                ('picture_rear', models.TextField(blank=True, null=True)),
                ('pictures', models.TextField(blank=True, null=True)),
                ('date_mod', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'enclosuremodels',
                'managed': True,
            },
        ),
    ]
