# Generated by Django 4.1 on 2022-09-01 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenterdata', '0002_delete_computers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cables',
        ),
        migrations.DeleteModel(
            name='Cartridges',
        ),
        migrations.DeleteModel(
            name='Consumables',
        ),
        migrations.DeleteModel(
            name='Devicesimcards',
        ),
        migrations.DeleteModel(
            name='Enclosures',
        ),
        migrations.DeleteModel(
            name='Monitors',
        ),
        migrations.DeleteModel(
            name='Networkequipments',
        ),
        migrations.DeleteModel(
            name='Pdus',
        ),
        migrations.DeleteModel(
            name='Phones',
        ),
        migrations.DeleteModel(
            name='Printers',
        ),
        migrations.DeleteModel(
            name='Racks',
        ),
        migrations.DeleteModel(
            name='Softwares',
        ),
        migrations.DeleteModel(
            name='Unmanageds',
        ),
    ]
