# Generated by Django 4.1 on 2022-09-01 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenterdata', '0003_delete_cables_delete_cartridges_delete_consumables_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cablestrands',
        ),
        migrations.DeleteModel(
            name='Cabletypes',
        ),
        migrations.DeleteModel(
            name='Cartridgeitems',
        ),
        migrations.DeleteModel(
            name='CartridgeitemsPrintermodels',
        ),
        migrations.DeleteModel(
            name='Cartridgeitemtypes',
        ),
        migrations.DeleteModel(
            name='Computermodels',
        ),
        migrations.DeleteModel(
            name='ComputersItems',
        ),
        migrations.DeleteModel(
            name='Computertypes',
        ),
        migrations.DeleteModel(
            name='Consumableitems',
        ),
        migrations.DeleteModel(
            name='Consumableitemtypes',
        ),
        migrations.DeleteModel(
            name='Devicesimcardtypes',
        ),
        migrations.DeleteModel(
            name='ItemsEnclosures',
        ),
        migrations.DeleteModel(
            name='ItemsRacks',
        ),
        migrations.DeleteModel(
            name='Monitormodels',
        ),
        migrations.DeleteModel(
            name='Monitortypes',
        ),
        migrations.DeleteModel(
            name='Networkequipmentmodels',
        ),
        migrations.DeleteModel(
            name='Networkequipmenttypes',
        ),
        migrations.DeleteModel(
            name='PdusPlugs',
        ),
        migrations.DeleteModel(
            name='PdusRacks',
        ),
        migrations.DeleteModel(
            name='Phonemodels',
        ),
        migrations.DeleteModel(
            name='Phonepowersupplies',
        ),
        migrations.DeleteModel(
            name='Phonetypes',
        ),
        migrations.DeleteModel(
            name='Printermodels',
        ),
        migrations.DeleteModel(
            name='PrintersCartridgeinfos',
        ),
        migrations.DeleteModel(
            name='Printertypes',
        ),
        migrations.DeleteModel(
            name='Softwarecategories',
        ),
        migrations.DeleteModel(
            name='Softwarelicenses',
        ),
        migrations.DeleteModel(
            name='Softwareversions',
        ),
    ]
