# Generated by Django 4.0.5 on 2022-11-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entities_id', models.PositiveIntegerField()),
                ('is_recursive', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('ldap_field', models.CharField(blank=True, max_length=255, null=True)),
                ('ldap_value', models.TextField(blank=True, null=True)),
                ('ldap_group_dn', models.TextField(blank=True, null=True)),
                ('date_mod', models.DateTimeField(blank=True, null=True)),
                ('groups_id', models.PositiveIntegerField()),
                ('completename', models.TextField(blank=True, null=True)),
                ('level', models.IntegerField()),
                ('ancestors_cache', models.TextField(blank=True, null=True)),
                ('sons_cache', models.TextField(blank=True, null=True)),
                ('is_requester', models.IntegerField()),
                ('is_watcher', models.IntegerField()),
                ('is_assign', models.IntegerField()),
                ('is_task', models.IntegerField()),
                ('is_notify', models.IntegerField()),
                ('is_itemgroup', models.IntegerField()),
                ('is_usergroup', models.IntegerField()),
                ('is_manager', models.IntegerField()),
                ('date_creation', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'groups',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GroupsKnowbaseitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowbaseitems_id', models.PositiveIntegerField()),
                ('groups_id', models.PositiveIntegerField()),
                ('entities_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_recursive', models.IntegerField()),
                ('no_entity_restriction', models.IntegerField()),
            ],
            options={
                'db_table': 'groups_knowbaseitems',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GroupsReminders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminders_id', models.PositiveIntegerField()),
                ('groups_id', models.PositiveIntegerField()),
                ('entities_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_recursive', models.IntegerField()),
                ('no_entity_restriction', models.IntegerField()),
            ],
            options={
                'db_table': 'groups_reminders',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GroupsRssfeeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rssfeeds_id', models.PositiveIntegerField()),
                ('groups_id', models.PositiveIntegerField()),
                ('entities_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_recursive', models.IntegerField()),
                ('no_entity_restriction', models.IntegerField()),
            ],
            options={
                'db_table': 'groups_rssfeeds',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GroupsUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_id', models.PositiveIntegerField()),
                ('groups_id', models.PositiveIntegerField()),
                ('is_dynamic', models.IntegerField()),
                ('is_manager', models.IntegerField()),
                ('is_userdelegate', models.IntegerField()),
            ],
            options={
                'db_table': 'groups_users',
                'managed': True,
                'unique_together': {('users_id', 'groups_id')},
            },
        ),
        migrations.CreateModel(
            name='GroupsProblems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problems_id', models.PositiveIntegerField()),
                ('groups_id', models.PositiveIntegerField()),
                ('type', models.IntegerField()),
            ],
            options={
                'db_table': 'groups_problems',
                'managed': True,
                'unique_together': {('problems_id', 'type', 'groups_id')},
            },
        ),
    ]
