# Generated by Django 4.0.5 on 2023-01-16 02:02

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('assistance', '0002_alter_users_managers_users_date_joined_users_email_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='groups',
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='groups',
            name='id',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='name',
        ),
        migrations.AddField(
            model_name='groups',
            name='group_ptr',
            field=models.OneToOneField(auto_created=True, default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group'),
            preserve_default=False,
        ),
    ]
